# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07a5bee1ef47d27514e25f2aae3af0d8"
name = "Notedesk"
handle = "notedesk-2"
application_url = "https://notedesk-app--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "test-store-0089.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://notedesk-app--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
